repos:
  - hooks:
      - id: check-ast
      - id: check-toml
      - id: check-xml
      - id: check-yaml
#      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: forbid-new-submodules
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 22.10.0
#  - hooks:
#      - id: commitizen
#      - id: commitizen-branch
#        stages:
#          - push
#    repo: https://github.com/commitizen-tools/commitizen
#    rev: v2.35.0
#  - hooks:
#      - id: prettier
#    repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.0.0-alpha.0
#  - hooks:
#      - id: autopep8
#    repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.7.0
#  - hooks:
#      - id: pyupgrade
#    repo: https://github.com/asottile/pyupgrade
#    rev: v3.0.0
#  - hooks:
#      - id: dead
#    repo: https://github.com/asottile/dead
#    rev: v1.5.0
