language: python

python:
  - 2.7.9

dist: xenial
sudo: false

env:
  - TRAVIS_NODE_VERSION="5.6.0"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install --quiet
  - bower install

install:
    - pip install --upgrade pip
    - pip install --upgrade tox

script:
  - grunt travis
  - tox -v --recreate

cache:
  directories:
    - $HOME/.cache/pip
    - bower_components
    - node_modules

after_failure:
  - cat ./Logs/sickrage.log

after_success:
  - chmod +x ./update-translations.sh
  - ./update-translations.sh

notifications:
  irc: "irc.freenode.net#sickrage-builds"
  email:
    on_success: change
    on_failure: change
