language: python

python:
  - 3.7

dist: xenial
sudo: false

env:
  - TRAVIS_NODE_VERSION="14.0.0"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/nvm-sh/nvm.git ~/.nvm && (cd ~/.nvm &&
    git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g grunt-cli bower xo webpack
  - yarn --silent
  - bower install

install:
  - pip install --upgrade pip
  - pip install --upgrade tox
  - pip install --upgrade babel mako crowdin-cli-py

script:
  - xo && tox -v --recreate -e "py37-{flake8,linux}"

cache:
  directories:
    - $HOME/.cache/pip
    - bower_components
    - node_modules

after_failure:
  - cat ./tests/Logs/sickchill.log

after_success:
  # don't run if any of these are NOT met
  - if ! { [[ ! -z "$CROWDIN_API_KEY" ]] && [[ "$GH_CRED" =~ ^.+:.+$ ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]
    && [[ "$TRAVIS_BRANCH" == "master" ]]; }; then exit 0; fi;
  - git --version
  - git config --global user.name "SickChill"
  - git config --global user.email miigotu@gmail.com
  - git config --global push.default current
  - git remote rm origin
  - git remote add origin https://$GH_CRED@github.com/$TRAVIS_REPO_SLUG.git
  - git fetch origin master develop --no-tags
  - grunt auto_update_trans

notifications:
  irc: "irc.freenode.net#sickchill-builds"
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/a5955679aa0a8ab5d1b7"
    on_success: change
    on_failure: change
    on_start: never
