language: python
python:
  - 2.6
  - 2.7

branches:
  only:
    - develop

install:
  - pip install cheetah

before_script:
 - chmod +x ./tests/all_tests.py

script:
  - ./tests/all_tests.py

notifications:
  irc: "irc.freenode.net#sickrage-updates"